# Generated by Django 6.0.1 on 2026-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Reason for rejection or approval notes', null=True),
        ),
    ]
