# Generated by Django 6.0.1 on 2026-03-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'HR / Admin'), ('manager', 'Department Manager'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
