# Generated by Django 6.0.1 on 2026-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Hide from Department Managers'),
        ),
    ]
